apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  # persistentVolumeReclaimPolicy: Recycle
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2

# kubectl get storageclass #Find out the storage classes available
# kubectl create -f .\k-persistent-volume.yaml
# kubectl get pv