apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
