apiVersion: v1
kind: Service
metadata:
  name: kk-flask-app-service
spec:
  selector:
    app: kk-flask-app-k8s
  ports:
    - protocol: TCP
      port: 5050
      nodePort: 30007
      targetPort: 5000
  type: NodePort
  # type: LoadBalancer